"""Generate smooth UI sprites. Pillow is needed only when rebuilding them."""
import base64
import math
from pathlib import Path

from PIL import Image, ImageDraw
from make_icon import _draw as draw_logo

SCALE = 6
SIZE = (70, 32)
COLORS = {
    True: {"normal": "#7c6cff", "hover": "#8f82ff", "pressed": "#6857e6", "disabled": "#1e2330"},
    False: {"normal": "#1e2330", "hover": "#39415a", "pressed": "#161a24", "disabled": "#1e2330"},
}


def draw_switch(checked, state, focused):
    image = Image.new("RGBA", (SIZE[0] * SCALE, SIZE[1] * SCALE))
    draw = ImageDraw.Draw(image)
    def bounds(values):
        return tuple(round(value * SCALE) for value in values)
    if focused:
        draw.rounded_rectangle(bounds((0.5, 0.5, 69.5, 31.5)), radius=15.5 * SCALE,
                               outline="#eceef6", width=SCALE)
    draw.rounded_rectangle(bounds((2, 2, 68, 30)), radius=14 * SCALE,
                           fill=COLORS[checked][state])
    center = 54 if checked else 16
    draw.ellipse(bounds((center - 10, 6.7, center + 10, 26.7)), fill=(0, 0, 0, 40))
    draw.ellipse(bounds((center - 10, 6, center + 10, 26)),
                 fill="#5f6884" if state == "disabled" else "#ffffff")
    return image.resize(SIZE, Image.Resampling.LANCZOS)


def draw_navigation_icon(name, color):
    """Draw consistent outline icons at 6x resolution, then antialias to 18px."""
    size = 18
    image = Image.new("RGBA", (size * SCALE, size * SCALE))
    draw = ImageDraw.Draw(image)
    width = round(1.4 * SCALE)
    if name == "settings":
        points = []
        for tooth in range(8):
            angle = tooth * math.tau / 8
            for offset, radius in ((-18, 6.1), (-12, 7.9), (12, 7.9), (18, 6.1)):
                theta = angle + math.radians(offset)
                points.append(((9 + radius * math.cos(theta)) * SCALE,
                               (9 + radius * math.sin(theta)) * SCALE))
        draw.line(points + [points[0]], fill=color, width=width, joint="curve")
        draw.ellipse(tuple(value * SCALE for value in (6.3, 6.3, 11.7, 11.7)),
                     outline=color, width=width)
    elif name == "back":
        draw.line([(14 * SCALE, 9 * SCALE), (4 * SCALE, 9 * SCALE)], fill=color, width=width)
        draw.line([(8 * SCALE, 4.5 * SCALE), (3.5 * SCALE, 9 * SCALE), (8 * SCALE, 13.5 * SCALE)],
                  fill=color, width=width, joint="curve")
    return image.resize((size, size), Image.Resampling.LANCZOS)


def main():
    from io import BytesIO
    lines = [
        '"""Generated by make_toggle_graphics.py; no Pillow needed at runtime."""',
        "", "SWITCH_IMAGES = {",
    ]
    for checked in (False, True):
        for state in ("normal", "hover", "pressed", "disabled"):
            for focused in (False, True):
                buffer = BytesIO()
                draw_switch(checked, state, focused).save(buffer, format="PNG", optimize=True)
                encoded = base64.b64encode(buffer.getvalue()).decode("ascii")
                lines.append(f"    {(checked, state, focused)!r}: {encoded!r},")
    lines.append("}\n")
    buffer = BytesIO()
    draw_logo(46).save(buffer, format="PNG", optimize=True)
    lines.append(f"LOGO_IMAGE = {base64.b64encode(buffer.getvalue()).decode('ascii')!r}\n")
    lines.append("SURFACE_CORNERS = {")
    # Nine-slice corners let Canvas panels resize without stretching the curves.
    pairs = {
        ("#7c6cff", "#7c6cff"), ("#8f82ff", "#8f82ff"), ("#6857e6", "#6857e6"),
        ("#1e2330", "#272d3b"), ("#39415a", "#39415a"), ("#161a24", "#272d3b"),
        ("#161a24", "#161a24"), ("#11141d", "#272d3b"), ("#11141d", "#7c6cff"),
        ("#11141d", "#f87171"), ("#161a29", "#303653"), ("#1d2236", "#7c6cff"),
        ("#161a29", "#7c6cff"),
    }
    pairs.update((fill, "#eceef6") for fill, _ in tuple(pairs))
    for radius in (8, 11, 12, 13, 16, 20):
        corner = radius + 2
        size = 2 * corner + 1
        for fill, border in sorted(pairs):
            sprite = Image.new("RGBA", (size * SCALE, size * SCALE))
            draw = ImageDraw.Draw(sprite)
            draw.rounded_rectangle((SCALE, SCALE, (size - 2) * SCALE, (size - 2) * SCALE),
                                   radius=radius * SCALE, fill=fill, outline=border, width=SCALE)
            sprite = sprite.resize((size, size), Image.Resampling.LANCZOS)
            encoded_corners = []
            regions = [(x, y, x + corner, y + corner) for x, y in
                       ((0, 0), (size - corner, 0), (0, size - corner), (size - corner, size - corner))]
            regions += [(corner, 0, corner + 1, corner),
                        (corner, size - corner, corner + 1, size),
                        (0, corner, corner, corner + 1),
                        (size - corner, corner, size, corner + 1)]
            for region in regions:
                buffer = BytesIO()
                sprite.crop(region).save(buffer, format="PNG", optimize=True)
                encoded_corners.append(base64.b64encode(buffer.getvalue()).decode("ascii"))
            lines.append(f"    {(fill, border, radius)!r}: {tuple(encoded_corners)!r},")
    lines.append("}\n")
    lines.append("DROP_ICONS = {")
    for color in ("#8490ad", "#7c6cff"):
        sprite = Image.new("RGBA", (36 * SCALE, 36 * SCALE))
        draw = ImageDraw.Draw(sprite)
        for points in (((18, 2), (18, 24)), ((11, 17), (18, 24), (25, 17)),
                       ((4, 23), (4, 33), (32, 33), (32, 23))):
            draw.line([(x * SCALE, y * SCALE) for x, y in points], fill=color, width=2 * SCALE, joint="curve")
            for x, y in points:
                draw.ellipse(((x - 1) * SCALE, (y - 1) * SCALE, (x + 1) * SCALE, (y + 1) * SCALE), fill=color)
        buffer = BytesIO()
        sprite.resize((36, 36), Image.Resampling.LANCZOS).save(buffer, format="PNG", optimize=True)
        lines.append(f"    {color!r}: {base64.b64encode(buffer.getvalue()).decode('ascii')!r},")
    lines.append("}\n")
    lines.append("BUTTON_ICONS = {")
    for name in ("settings", "back"):
        for color in ("#eceef6", "#5f6884"):
            buffer = BytesIO()
            draw_navigation_icon(name, color).save(buffer, format="PNG", optimize=True)
            encoded = base64.b64encode(buffer.getvalue()).decode("ascii")
            lines.append(f"    {(name, color)!r}: {encoded!r},")
    lines.append("}\n")
    Path(__file__).with_name("toggle_graphics.py").write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
